### ISSUE TITLE
如何修改前端页面

### ISSUE THREAD

**Issue by HayatoOvO** [lewkamtao/PicHub#1]
作者您好！您的项目非常好，我想对您的项目的前端页面进行添加/修改，但是我对 JavaScript 这方面不太精通，如果想对前端页面进行修改或添加，我该怎么操作？谢谢您。

**Comment by lewkamtao** [comment]
你好，很高兴你认可我的项目，这个项目基础是要求会vue3，一时之间没办法教你怎么操作，还比较复杂呢。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Future_Maker ***@***.***&gt;;
发送时间：2022年4月24日(星期天) 晚上6:07
收件人："lewkamtao/PicHub" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lewkamtao/PicHub] 如何修改前端页面 (Issue #1)
-----------------------------------

 

 
作者您好！您的项目非常好，我想对您的项目的前端页面进行添加/修改，但是我对 JavaScript 这方面不太精通，如果想对前端页面进行修改或添加，我该怎么操作？谢谢您。

**Comment by HayatoOvO** [comment]
> 

好的，谢谢您。我去学习一下。
