### ISSUE TITLE
[bug]发现一些bug

### ISSUE THREAD

**Issue by kaxifakl** [lewkamtao/PicHub#6]
1.当文件夹过多时，scroll无法往下滚动
2.打包出来的文件无法部署在github page上
3.图片压缩库太大，导致网页加载慢
4.当部署在github上，且github开通page时，点击文件夹后，会进入github仓库页面跳转，因为文件夹按钮是a标签，带地址，点击后会向当前域名+地址跳转

**Comment by HayatoOvO** [comment]
> 1.当文件夹过多时，scroll无法往下滚动 2.打包出来的文件无法部署在github page上 3.图片压缩库太大，导致网页加载慢 4.当部署在github上，且github开通page时，点击文件夹后，会进入github仓库页面跳转，因为文件夹按钮是a标签，带地址，点击后会向当前域名+地址跳转

Answer：
1. 锁定问题了，没有安装滚动条，最近一周我想办法修复，目前的解决方法是可以先切换到关于界面就可以正常 scroll。
2. 我记得这个部署在 GitHub Pages 上有点悬，要真想托管部署，可以选择 Cloudflare Pages 或 Vercel Apps。
3. 这个我没有什么好方法解决，等 Lew 大大不忙了再让他解决（悲
4. 一下恍惚了没听懂，可以讲得详细一点，或者如果可以复现，说明一下复现方法。

**Comment by kaxifakl** [comment]
3.当前压缩库可能会导致透明背景的图片背景变成黑色
4.其实就是a标签指向的问题，点击时，a标签地址会加上当前域名地址，可能会跳转到其他页面去，假如部署在githubpage上，就会跳转到某个仓库页面去

**Comment by lewkamtao** [comment]
涉及透明图片的时候 应该选择上传原图，原图功能就是为了这个设计的，另外一点不是很明白。

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："kaxifakl ***@***.***&gt;;
发送时间：2022年8月10日(星期三) 中午1:49
收件人："lewkamtao/PicHub" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lewkamtao/PicHub] [bug]发现一些bug (Issue #6)
-----------------------------------

 


3.当前压缩库可能会导致透明背景的图片背景变成黑色
 4.其实就是a标签指向的问题，点击时，a标签地址会加上当前域名地址，可能会跳转到其他页面去，假如部署在githubpage上，就会跳转到某个仓库页面去
